### ISSUE TITLE
Undeclared dependency on DBD::SQLite

### ISSUE THREAD

**Issue by andk** [nekokak/p5-Data-RuledCluster#4]
As per subject. Grep:

http://search.cpan.org/grep?release=Data-RuledCluster-0.06;string=SQLite;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/75203833

HTH&&Thanks,

**Comment by karupanerura** [comment]
@andk thank you for your reporting. and I'm sorry for the late reply. I'll fix it soon.
